# ================= BACKEND SERVICE =================
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: project-root
spec:
  selector:
    app: backend
  ports:
    - port: 6000
      targetPort: 6000
  type: ClusterIP
---
# ================= FRONTEND SERVICE =================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: project-root
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
